<!DOCTYPE html>
<html lang="en-us">
    <head>
		
		
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>Introduction Part 1: U.S. &middot; My New Hugo Site</title>

		
		<link rel="stylesheet" href="/css/style.css">
		<link rel="stylesheet" href="/css/fonts.css">
		
		<link rel="icon" href="/favicon.ico"/>
		<link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png">
		<link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png">

		
		<link href="" rel="alternate" type="application/rss+xml" title="My New Hugo Site" />

		<script src="/js/darkmode.js"></script>
	</head>

    <body>
        		<nav class="nav">
			<div class="nav-container">
				<a href="/">
					
						<h2 class="nav-title">My New Hugo Site</h2>
					
				</a>
				<ul>
    
    
</ul>
			</div>
		</nav>

        <div id="darkModeToggle" onclick="toggleDarkMode()">
  &#9680; 
</div>

        

<main>
	


        <div class="post">
		<div class="post-info">
    <span>Written by</span>
        Kate Lim-Shim
        <br>
        <span>on&nbsp;</span><time datetime="2022-09-14 00:00:00 &#43;0000 UTC">September 14, 2022</time>
</div>

		<h1 class="post-title">Introduction Part 1: U.S.</h1>
<div class="post-line"></div>

		

		


<div id="describing-trends-in-the-popular-vote" class="section level2">
<h2>Describing Trends in the Popular Vote</h2>
<p>In this first blog, I will attempt to answer two questions:
1) How competitive are midterm elections in the U.S.?
2) Which states vote blue/red and how consistently?
Based on all midterm elections from 1950 to 2018, I will use visualizations to address these questions.</p>
<p>In the <a href="https://www.acsu.buffalo.edu/~jcampbel/documents/Congress02.pdf">Decline of Competition and Change in Congressional Elections in Congress Responds to the Twentieth Century</a>, Professors Campbell and Juerk claim that without competition, elections are meaningless. Competition, the chance for voters to “redirect their representation, is what makes elections important instruments of representative government.” It is important to discuss the importance of elections at both the state and national level to learn how <a href="https://www.cnn.com/2022/08/06/politics/redistricting-what-matters">historical trends</a> of decreasing competitiveness in congressional districts or deliberate attempts to change election outcomes such as redistricting can affect and predict future elections. I created a couple tables below to show the changing competitiveness of midterm elections since 1950.</p>
<pre><code>## Rows: 37 Columns: 16
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (2): AreaAll, winner_party
## dbl (9): year, R_seats, D_seats, Other_seats, R_totalvote_pct, D_totalvote_p...
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre><code>## # A tibble: 18 × 5
##     year winner_party winning_vote_margin Tot_Major_votes Margin_Share_of_Total
##    &lt;dbl&gt; &lt;chr&gt;                      &lt;dbl&gt;           &lt;dbl&gt;                 &lt;dbl&gt;
##  1  1950 R                         243541        41606813               0.00585
##  2  1954 D                        2130550        44315766               0.0481 
##  3  1958 D                        4508241        45378291               0.0993 
##  4  1962 D                        3552077        61875007               0.0574 
##  5  1966 D                         895976        52296098               0.0171 
##  6  1970 D                        4506685        53336395               0.0845 
##  7  1974 D                        8802599        51376441               0.171  
##  8  1978 D                        4696635        54478965               0.0862 
##  9  1982 D                        7792034        63385194               0.123  
## 10  1986 D                        6158591        59357761               0.104  
## 11  1990 D                        4999982        61104350               0.0818 
## 12  1994 R                        4975404        69224438               0.0719 
## 13  1998 R                         772521        63736593               0.0121 
## 14  2002 R                        3629633        71146209               0.0510 
## 15  2006 D                        6396747        78165893               0.0818 
## 16  2010 R                        5625166        80951688               0.0695 
## 17  2014 R                        4400874        75658852               0.0582 
## 18  2018 D                        9743499       111977671               0.0870</code></pre>
</div>
<div id="competitiveness" class="section level2">
<h2>Competitiveness</h2>
<p>Looking at the 2018 midterm elections, as the winning party, the Democrats won 54.35% of the nationwide votes and 235 seats. According to a <a href="https://ig.ft.com/us-midterm-elections/">Financial Times report</a>, “The Republican Party lost control of the House as Democrats capitalized on anti-Trump anger and the retirement of a large number of incumbent Republicans. Of the 111 seats rated “competitive” by the Cook Political Report, 98 were Republican-held." Additionally, only 30 seats were classed as a toss up, almost all held by Republicans. House seats that flipped to Democrat (Democrats needed 23 seats to win but they actually flipped 44) included Pennsylvania’s 7th District and Florida’s 26th District), compared to the 3 seats that were previously held by Democrats that flipped to Republicans as shown by <a href="https://www.pewresearch.org/methods/2020/09/08/democrats-made-gains-from-multiple-sources-in-2018-midterm-victories/">the Pew Research Center’s Demographic Profile</a>.</p>
<p>Looking at the table with all midterm elections (1948 - 2020) with winning vote margin and margin vote share of the total, we can see the trends of competitiveness in midterm elections. The <a href="https://www.google.com/url?q=https://constitutioncenter.org/blog/how-midterm-elections-have-changed-congress-since-1946&amp;sa=D&amp;source=docs&amp;ust=1667485614256346&amp;usg=AOvVaw0pLGCduMUX2TMyBq0r6ews">Constitution Center</a> provides some context to the stronghold of Congress: “Since 1946, when Republicans ended a 14-year period of total Democratic control in Congress, midterm elections have been mostly contested starting in the Reagan era….. the picture [for competitiveness of midterms] has been mixed.” Looking at the post World War II midterms, it is important to understand the historical background: in 1946 Republicans took control of the House and Senate, ending a 14-year period of Democratic control of both chambers, one that started with Franklin D. Roosevelt’s election in 1932. In the 1950 midterms, the Democrats kept control of both chambers, which they had taken back in the 1948 general election. Although beyond this election they kept control of both the House and Senate, it was not a secure win for the Democrats as the election took place during the Korean War and Harry Truman’s second term — by this time, Truman was already on the path to becoming one of the most unpopular presidents.</p>
<pre><code>## [1] 0.0727714</code></pre>
<pre><code>## # A tibble: 1 × 3
##   D_seats D_majorvote_pct winner_party
##     &lt;dbl&gt;           &lt;dbl&gt; &lt;chr&gt;       
## 1     225            52.4 D</code></pre>
<pre><code>## # A tibble: 1 × 3
##   D_seats D_majorvote_pct winner_party
##     &lt;dbl&gt;           &lt;dbl&gt; &lt;chr&gt;       
## 1     255            54.2 D</code></pre>
<pre><code>## # A tibble: 1 × 3
##   D_seats D_majorvote_pct winner_party
##     &lt;dbl&gt;           &lt;dbl&gt; &lt;chr&gt;       
## 1     235            54.4 D</code></pre>
<p>The tables above show that in comparison to the mean margin share of the total of about 7.28%, 1950 was the most competitive midterm election with Republicans barely winning by a slim margin of 243,541 votes, which translated to about 0.585% of the total votes. In this election, Democrats won with about 52.4% of the votes, which translated to a narrow 225 seats. In contrast, 1974 was the least competitive midterm election by far with a secure Democratic win in which their margin share of total votes was 17.134%. The <a href="https://library.cqpress.com/cqalmanac/document.php?id=cqal74-1222893">CQ Press</a> reported that “Republicans paid the bill in November 1974 for two years of scandal and economic decline, losing heavily in congressional and gubernatorial elections throughout the country and slipping deeper into a minority status that was unlikely to end in the foreseeable future.” As a result of this, Democrats gained 43 seats in the House, 3 in the Senate and 4 Governor positions. Even though the Democratic popular vote share was only about 54.22%, Democrats ended up with a whopping 255 seats as part of this landslide victory. Most recently in 2018, there was a higher overall turnout than other previous midterms, with 111,977,671 people voting, hitting a new record since 1914. In large part due to Trump driving the voting eligible population both for and against him, the Democrats won with a margin share of 8.701%. With 54.35% of the majority vote share, the Democrats took 235 seats, which was neither a landslide nor a narrow win.</p>
<pre><code>## # A tibble: 2 × 2
##   winner     races
##   &lt;chr&gt;      &lt;int&gt;
## 1 Democrat      12
## 2 Republican     6</code></pre>
<p>Overall, out of 18 midterm elections, there were 12 Democratic wins and only 6 Republican wins. This does not tell the full story of competitiveness in midterm elections since there are historical and other contextual considerations that are important. The 2018 voting patterns were defined by stark demographic and educational divisions, taking the cake in competitiveness. Other potential influencing factors of election results include popularity of incumbent president, standards of living, changing contentious issues, political socialization, and tolerance of opposing political views represented in the media.</p>
<p><img src="http://example.org/post/2022-09-14-blog-post-1/index_files/figure-html/unnamed-chunk-7-1.png" width="672" />
## Which states vote blue/red and how consistently?
To answer this question, I created a map above of all midterm elections over 1950 and 2018 with a district breakdown. Southern states including Texas, Louisiana, Arkansas, Mississippi, Alabama, Georgia, and South Carolina between 1950 and 1958 midterm elections consistently showed strong support for Democrats but in the midterms from 1962-1990, they began to move towards leaning purple, away from being strong blue. The 1994 midterms during Bill Clinton’s first term show the first divergence of the South to Republican. A similar pattern can be found in the Northeast South Atlantic. Overall, coastal regions of the U.S. voted more Democrat while non-coastal areas had mixed results. The Pacific West leaned towards Republican but then slowly shifted on the scale towards voting for Democrats. The Mountain West produced mixed results and not many patterns can be drawn. The unpredictable behavior of states like Nevada, Idaho, Colorado, Wyoming, and New Mexico show that there is no consistent voting trend. There may be some lean overall, but the variance from midterm to midterm was historically, in this region, fairly inconsistent. The Midwest West North Central region tended towards Republicans, then towards Democrats, and then began to lightly support Republicans. For example, Minnesota in 1950 and 1966 voted Republican, then around the 1970s started to lean more Democrat. The Midwest East North Central region has been ambiguous, but started leaning towards Democrats. The Northeast Middle Atlantic has consistently shown a Democratic stronghold.</p>
<p><img src="http://example.org/post/2022-09-14-blog-post-1/index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The 2014 election, which happened in the middle of President Obama’s second term, yielded impressive results for Republicans and is often referred to as the “Red Wave” election. Issues plaguing the Obama administration such as the handling of the Ebola outbreak and attempt for better social welfare (the push for the ACA and higher minimum wages) had a strong effect on the results. But the most important issue that facilitated this red wave was unsurprisingly, the economy. <a href="https://abcnews.go.com/Politics/national-exit-poll-reveals-major-voter-discontent-midterm/story?id=26688877">National exit polling</a> revealed major voter discontent with the direction of the country and its economic prospects.</p>
<p>Some notable states that voted blue were California, Oregon, New York, Vermont with the highest Democrat vote share margin found in Massachusetts. But many states voted red, including but not limited to Wyoming, Oklahoma, Alabama, South Carolina, Utah, and Louisiana with the highest Republican vote share margin found in Wyoming and Oklahoma. Compared to previous elections, Republicans kept their seats and also gained key seats in Nevada, Texas, and Maine, among others.</p>
<p><img src="http://example.org/post/2022-09-14-blog-post-1/index_files/figure-html/unnamed-chunk-11-1.png" width="672" />
Compared to the 2014 midterms, the 2018 midterms illustrated the overall pattern of loss of support for Republicans. A prime example of this can be found in the South: among other states, Texas, Georgia, and Florida show a lower GOP voteshare. Additionally, along with several Midwest states, it can be seen that Virginia and Pennsylvania lean much more towards purple than in the 2014 election. States that were previously known to be swings states or leaned Republican such as Nevada, Illinois, Arizona, Colorado, or Iowa are shown to lose GOP voteshare. States in the Northeast (New York, Vermont, New Hampshire, New Jersey, and Delaware) and the Pacific West (Washington, Oregon, and California) were part of this trend as well. <a href="https://www.google.com/url?q=https://www.brookings.edu/research/2018-voter-turnout-rose-dramatically-for-groups-favoring-democrats-census-confirms/&amp;sa=D&amp;source=docs&amp;ust=1667532446440955&amp;usg=AOvVaw3sV2hTtiFvpwlAcRBVLMzz">A Brookings Institute report</a> on the 2018 election shed light on new data that the Democrats’ “blue wave” takeover of the House was driven by extraordinarily high levels of voter turnout among voting blocs that lean democratic. “The turnout surge favored youth,”new minorities," and White college graduates.</p>
<p><img src="http://example.org/post/2022-09-14-blog-post-1/index_files/figure-html/unnamed-chunk-14-1.png" width="672" />
The above map breaks down 2014 voteshare margin by district, giving us insight into which districts heavily leaned towards blue or red and which ones gravitated towards the middle. In the case of Louisiana for example, the 3rd and 4th congressional districts had the highest Republican vote share margin. In the 3rd district, there were two Republicans running against one another, another explanation for the high red vote share margin. In the 4th district, there was one Republican candidate and a Libertarian candidate, with the Democrat withdrawing from the election, explaining why the margin was so high for Republicans. The districts that voted blue were California’s 20th district and Texas’s 28th district, among others. The districts that voted red were California’s 4th district, Washington’s 4th district, and Texas’s 11th district, among others. The reason I chose to visualize this map through a state basis and later through congressional districts is because the state basis could show a general pattern of vote share margin, and the individual congressional districts could give more insight into the specific district elections, such as in the example of Louisiana.</p>
<p><img src="http://example.org/post/2022-09-14-blog-post-1/index_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>In a comparison between the 2016 presidential election and 2018 midterms, <a href="https://www.google.com/url?q=https://www.brookings.edu/research/a-vast-majority-of-counties-showed-increased-democratic-support-in-2018-house-election/&amp;sa=D&amp;source=docs&amp;ust=1667485614262219&amp;usg=AOvVaw147HVI3FRGO7N84NixtnYE">The Brookings Institution</a> found a reduced Republican margin and increased Democrat margin that in most counties (including those won my Republicans in 2018), more voters favored Democrats. “In a majority of counties (2,445 of 3,111)–— irrespective of whether the final 2018 vote favored Republican or Democratic candidates—there was a positive D-R margin shift between 2016 and 2018 (meaning either a greater Democratic advantage or a smaller Republican advantage).” They found that 83% of all voters were from counties that increased their D-R margins between 2016 and 2018. Compared to the 2016 presidential election, many districts, most notably New Mexico, Montana, and Wyoming, increased their Democrat voting margin. 26% of voters lived in counties that increased their D-R margins by more than 10 and an impressive 57% of voters lived in counties that increased their D-R margins by 0 to 9.</p>
<p>I made the same map for the 2018 midterms to find the difference in vote breakdown by district. Overall, the 2014 and 2018 elections seem similar, but there are less districts which historically favored Republicans that start to lean Blue. In the map, the districts which I pointed out that voted red during the 2014 midterms (California’s 4th district, Washington’s 4th district, and Texas’s 11th district) had all visibly decreased their support for the GOP. An exception to this trend of previously Republican leaning districts shifting towards Democrats is California’s 8th district, which had a record-high GOP voteshare. Through my findings and research, it is clear that although the 2018 election was not a high margin of victory for Democrats, the sheer voter turnout and turnout among Democrat-voting populations cemented a Democratic stronghold and higher expectations for the party’s performance in future elections. Reading into the patterns of vote share in different parts of the country, it is in some ways reassuring to know that there is a pendulum of trends in voting so that even if there are some counties/states which vote consistently blue or red, nothing is for certain and there is no such thing as a guaranteed stronghold.</p>
</div>


		
	</div>

	<div class="pagination">
		<a href="/post/2022-09-14-introduction-part-2-illinois/" class="left arrow">&#8592;</a>
		<a href="/post/2022-10-03-blog-4-incumbency/" class="right arrow">&#8594;</a>

		<a href="#" class="top">Top</a>
	</div>
</main>


        		<footer>
			
			<span>
			&copy; <time datetime="2022-12-13 11:24:20.929681 -0500 EST m=&#43;0.224108982">2022</time> . Made with <a href='https://gohugo.io'>Hugo</a> using the <a href='https://github.com/EmielH/tale-hugo/'>Tale</a> theme.
			</span>
		</footer>

    </body>
</html>
