<!DOCTYPE html>
<html lang="en-us">
    <head>
		
		
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>Blog 4 - Incumbency &middot; My New Hugo Site</title>

		
		<link rel="stylesheet" href="/css/style.css">
		<link rel="stylesheet" href="/css/fonts.css">
		
		<link rel="icon" href="/favicon.ico"/>
		<link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png">
		<link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png">

		
		<link href="" rel="alternate" type="application/rss+xml" title="My New Hugo Site" />

		<script src="/js/darkmode.js"></script>
	</head>

    <body>
        		<nav class="nav">
			<div class="nav-container">
				<a href="/">
					
						<h2 class="nav-title">My New Hugo Site</h2>
					
				</a>
				<ul>
    
    
</ul>
			</div>
		</nav>

        <div id="darkModeToggle" onclick="toggleDarkMode()">
  &#9680; 
</div>

        

<main>
	


        <div class="post">
		<div class="post-info">
    <span>Written by</span>
        
        <br>
        <span>on&nbsp;</span><time datetime="2022-10-03 00:00:00 &#43;0000 UTC">October 3, 2022</time>
</div>

		<h1 class="post-title">Blog 4 - Incumbency</h1>
<div class="post-line"></div>

		

		


<p><img src="http://example.org/post/2022-10-03-blog-4-incumbency/index_files/figure-html/unnamed-chunk-4-1.png" width="672" />
This first map visualizes actual voteshare at the district level in 2018, based on the Democrat vote margin percentage. The map holds many districts that are blue and those that lean towards blue. It means that there is a larger voteshare for Democrats (which is in their favor) at the district level.</p>
<p><img src="http://example.org/post/2022-10-03-blog-4-incumbency/index_files/figure-html/unnamed-chunk-5-1.png" width="672" />
This map visualizes expert predictions based on the Cook Political Report data at the district-level in 2018. There seems to be 1) a larger proportion of secure red districts and 2) stronger blue districts, especially along the West Coast. However, we must assess the first takeaway with a grain of salt: the overreporting of secure Republican districts may seem more than it actually is because the visualization of the data can mislead with the bigger areas of districts in rural areas.</p>
<p>Overall, the predictions are more extreme in both directions (in that there are more districts that are safe Democrat or safe Republican) than the actual voteshare. As Enos and Hersh show in their 2015 paper “Campaign Perceptions of Electoral Closeness: Uncertainty, Fear and Over-Confidence”, political campaign operatives tend to be overconfident in their candidates’ performance, skewing the perception of the election’s closeness.</p>
<p>Recent elections have only been stronger in support that polling may not be the most accurate tool in election forecasting. In his 2021 study “Failure and Success in Political Polling and Election Forecasting”, Andrew Gelman explains that the polls in both recent presidential elections with both Clinton and Biden are examples of the overstatement of Democratic strength, a pattern also seen in recent congressional elections. Through Gelman’s experience studying public opinion, he attributes the large proportion of swing in polls to a type of polling bias called “differential nonresponse”, in which supporters of candidates are more vocal in surveys when their candidate does well. This phenomenon, accompanied by high correlations between each party’s share of support in each poll and the percentage of partisans among respondents, only highlights the growing variable of partisanship. Gelman finds that there is a historical overestimate of Democrat performance due to factors such as this differential nonresponse and differential turnout. However, the 2018 elections were a place for polls to redeem their quality.</p>
<p><img src="http://example.org/post/2022-10-03-blog-4-incumbency/index_files/figure-html/unnamed-chunk-6-1.png" width="672" />
The third map shows exactly this result, with many polls yielding a difference of 0 in accuracy between the actual voteshare and the expert predictions. This meant that the 2018 predictions held consistent accuracy and if there were differences between the first two maps, they were small. The NYT article “What the Polls Got Right This Year, and Where They Went Wrong” found that while the 2018 expert predictions were a significant increase in accuracy compared to the 2016 elections, the polls underestimated Democrats in several states where they also underestimated Democrats in 2016 like California, New York, and Nevada. “Our polls did not overestimate Democrats in the less educated states and districts of the East, where one might expect the phenomenon to show up, though they did underestimate Democrats in California and the Southwest.” The 2018 expert predictions yielded many precise results. While there was error, it was small and mostly negative, underestimating Democrats’ performance and overestimating Republicans’. Examples can be found in Minnesota’s 7th district, which underestimated Republicans and Nevada’s 4th congressional district, which underestimated the Democrats. This type of error, which was also found in Florida, was to be expected, especially looking at the patterns from previous years. While recent polls from 2016 and 2020 give more and more reason to distrust polls, 2018 was a good year for expert accuracy and optimizing probabilistic forecasting tools to understand how the American public feels about upcoming elections.</p>
<pre><code>## Rows: 37 Columns: 31
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (4): AreaAll, winner_party, president_party, H_incumbent_party
## dbl (26): ID, year, Midterm, R_seats, D_seats, Other_seats, total_votes, R_v...
## lgl  (1): H_incumbent_party_winner
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre><code>## 
## Call:
## lm(formula = D_seats ~ GDP_Growth_Pct + US_CPI + US_Unemployment_Rate, 
##     data = EE_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -37.478 -19.793  -1.232  17.542  38.807 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          247.5442    17.7172  13.972 2.06e-15 ***
## GDP_Growth_Pct        -0.9832     1.7011  -0.578    0.567    
## US_CPI                -0.2596     0.0505  -5.141 1.22e-05 ***
## US_Unemployment_Rate   1.4595     0.8740   1.670    0.104    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 23.46 on 33 degrees of freedom
## Multiple R-squared:  0.4473, Adjusted R-squared:  0.3971 
## F-statistic: 8.903 on 3 and 33 DF,  p-value: 0.0001827</code></pre>
<pre><code>## 
## Call:
## lm(formula = D_seats ~ D_majorvote_pct_lag + GDP_Growth_Pct + 
##     US_CPI + US_Unemployment_Rate, data = EE_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -46.266 -14.179   0.233  15.271  45.687 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)          32.16837   75.92036   0.424  0.67470   
## D_majorvote_pct_lag   4.51176    1.56446   2.884  0.00708 **
## GDP_Growth_Pct       -3.00432    1.70586  -1.761  0.08807 . 
## US_CPI               -0.17638    0.05428  -3.250  0.00278 **
## US_Unemployment_Rate  0.08993    0.95129   0.095  0.92530   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.44 on 31 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.5594, Adjusted R-squared:  0.5025 
## F-statistic:  9.84 on 4 and 31 DF,  p-value: 2.939e-05</code></pre>
<pre><code>## 
## Call:
## lm(formula = D_seats ~ D_majorvote_pct_lag + GDP_Growth_Pct + 
##     US_CPI, data = EE_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -45.761 -14.137   0.123  15.319  45.801 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)         29.66162   70.02836   0.424  0.67472   
## D_majorvote_pct_lag  4.58906    1.31290   3.495  0.00141 **
## GDP_Growth_Pct      -3.06832    1.54132  -1.991  0.05511 . 
## US_CPI              -0.17426    0.04863  -3.583  0.00111 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.11 on 32 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.5593, Adjusted R-squared:  0.518 
## F-statistic: 13.54 on 3 and 32 DF,  p-value: 7.158e-06</code></pre>
<pre><code>## 
## Call:
## lm(formula = D_seats ~ D_majorvote_pct_lag + GDP_Growth_Pct + 
##     US_CPI + Pres_R, data = EE_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -44.932 -15.830  -0.609  15.512  47.780 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)         14.64954   78.03902   0.188  0.85232   
## D_majorvote_pct_lag  4.80193    1.40741   3.412  0.00181 **
## GDP_Growth_Pct      -2.80072    1.66530  -1.682  0.10265   
## US_CPI              -0.16660    0.05197  -3.205  0.00312 **
## Pres_R               3.86733    8.39654   0.461  0.64831   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.37 on 31 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.5623, Adjusted R-squared:  0.5058 
## F-statistic: 9.955 on 4 and 31 DF,  p-value: 2.668e-05</code></pre>
<pre><code>## 
## Call:
## lm(formula = H_incumbent_party_majorvote_pct ~ GDP_Growth_Pct, 
##     data = EE_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.1703 -1.7524 -0.2146  2.1449  6.2617 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     52.7003     0.9180  57.409   &lt;2e-16 ***
## GDP_Growth_Pct  -0.2937     0.2314  -1.269    0.213    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.335 on 35 degrees of freedom
## Multiple R-squared:  0.04398,    Adjusted R-squared:  0.01667 
## F-statistic:  1.61 on 1 and 35 DF,  p-value: 0.2128</code></pre>
<p><img src="http://example.org/post/2022-10-03-blog-4-incumbency/index_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre><code>## [1] 3.243329</code></pre>
<pre><code>## [1] 0.04398211</code></pre>
<pre><code>## 
## Call:
## lm(formula = H_incumbent_party_majorvote_pct ~ US_Unemployment_Rate, 
##     data = EE_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.3781 -1.6452  0.2231  2.4071  6.8927 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           48.5044     2.0687  23.447   &lt;2e-16 ***
## US_Unemployment_Rate   0.1875     0.1148   1.633    0.111    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.288 on 35 degrees of freedom
## Multiple R-squared:  0.07082,    Adjusted R-squared:  0.04427 
## F-statistic: 2.668 on 1 and 35 DF,  p-value: 0.1114</code></pre>
<p><img src="http://example.org/post/2022-10-03-blog-4-incumbency/index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre><code>## [1] 3.197479</code></pre>
<pre><code>## [1] 0.07082147</code></pre>
<pre><code>## 
## Call:
## lm(formula = H_incumbent_party_majorvote_pct ~ US_CPI, data = EE_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.7532 -2.2432 -0.2191  1.9532  5.6638 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 53.778661   0.885015  60.766  &lt; 2e-16 ***
## US_CPI      -0.017690   0.006372  -2.776  0.00877 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.088 on 35 degrees of freedom
## Multiple R-squared:  0.1805, Adjusted R-squared:  0.1571 
## F-statistic: 7.707 on 1 and 35 DF,  p-value: 0.008772</code></pre>
<p><img src="http://example.org/post/2022-10-03-blog-4-incumbency/index_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre><code>## [1] 3.002903</code></pre>
<pre><code>## [1] 0.1804671</code></pre>
<div id="conclusion-on-updated-model" class="section level2">
<h2>Conclusion on Updated Model:</h2>
<p>lm_1: y = pop vote = -0.2397(GDP Growth Pct) + 52.7003
lm_2: y = pop vote = 0.1875(US Unemployment Rate) + 48.5044
lm_3: y = pop vote = -0.017690(US_CPI) + 53.7787
note: For each model, the estimated coefficients for the independent variable indicates a marginal effect on the dependent variable, which is popular vote for the incumbent. Ex: For Model 1, a 1 unit increase (1% increase in annual GDP Growth Percentage) yields a decrease of 0.2397% in House Incumbent Party Majority Vote Percentage. For Model 2, a 1 unit increase (1% increase in the U.S. Unemployment Rate) yields an increase of 0.1875% in House Incumbent Party Majority Vote Percentage. For Model 3, a 1 unit increase (1% increase in the U.S. Consumer Price Index) yields a decrease of 0.01769% in House Incumbent Party Majority Vote Percentage. Below, I assess the accuracy of each of these models.</p>
<p>The GDP Growth Percentage seems to hold the lowest predictive power in estimating the marginal effect on the popular vote. With a relatively high mean-squared error of about 3.2433 and a low R squared value of 0.044, Model 1 has the lowest accuracy in the linear regression model predicting popular votes. Five Thirty-Eight found that “There is definitely a relationship between G.D.P. and election results. But, it isn’t a perfect one. Overall the r-squared for G.D.P. is .33 in elections since 1948. That is, about 33 percent of election results are explained by G.D.P., leaving about two-thirds of the results unexplained.”</p>
<p>The U.S. Unemployment Rate is in the middle with its predictive power with a mean-squared error of about 3.1975 and a R squared value of 0.0708. While there exists literature on the relationship between unemployment rate and approval rates of the President and Congress, there is a lack of clear information on the chances of re-election. Five Thirty-Eight ambiguously concluded that the data is not strong enough to prove a relationship between unemployment rate and popular vote, but “it is also not strong enough to disprove a relationship.”</p>
<p>CPI is a natural measure of inflation and when it goes up, it yields a decrease of 0.01769%, giving a conclusive effect. Out of all 3 models, the CPI factor has the smallest mean-squared error of about 3.0029, indicating that this is the best performing model and holds the highest predictive power out of all 3 in estimating the House Incumbent Party Majority Vote Percentage. Another reason this model may be the closest in accuracy of prediction is that it is the only one that is statistically significant. As the R squared value gets higher, it indicates how much variation of y values in the sample is captured by the fitted model’s predicted values, and how much can be explained by the estimation models. CPI has the highest R squared value of 0.1805. Even though about 82% of the variation is not captured, it is still the best predictive model we have on hand. Through Model 3, based on CPI, we find that if the CPI continuously increased over time, it is natural to see the continuously decreasing popular vote (predicted value in dots). The Pew Research Center found that inflation is a key factor in their voting decisions, and in the context of Democrats controlling the House and the presidency, personal financial ratings in response to inflation lean more negative, especially for Republicans. Overall, Democrat views of the economy, while negative, are still more positive than Republicans’. “The Electoral Impact of Unexpected Inflation and Economic Growth” by Harvey Palmer and Guy Whitten reveals through empirical analysis stronger electoral effects for unexpected inflation and growth, serving as reliable indicators of government competence to voters and therefore lending itself to higher or lower approval rates/incumbent popularity. Of course, there are many more economic factors of wellbeing that are more well-favored by political scientists, such as growth in real disposable income, but for the time being, CPI is most accurate.</p>
</div>


		
	</div>

	<div class="pagination">
		<a href="/post/2022-09-30-blog-1/" class="left arrow">&#8592;</a>

		<a href="#" class="top">Top</a>
	</div>
</main>


        		<footer>
			
			<span>
			&copy; <time datetime="2022-10-28 15:59:22.665895 -0400 EDT m=&#43;0.235046525">2022</time> . Made with <a href='https://gohugo.io'>Hugo</a> using the <a href='https://github.com/EmielH/tale-hugo/'>Tale</a> theme.
			</span>
		</footer>

    </body>
</html>
