---
title: Ground Game
author: Kate Lim-Shim
date: '2022-10-18'
slug: []
categories: []
tags: []
---



<pre><code>## 
## Call:
## lm(formula = voterTR ~ Close_E_D + Incumbent_R + MidtermE_D + 
##     Open_seat, data = Final_2012_2020_DF)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.28111 -0.05644  0.01246  0.07019  0.23198 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.591932   0.015360  38.537   &lt;2e-16 ***
## Close_E_D    0.032630   0.015349   2.126   0.0341 *  
## Incumbent_R  0.034581   0.016127   2.144   0.0326 *  
## MidtermE_D  -0.131268   0.010230 -12.832   &lt;2e-16 ***
## Open_seat   -0.003483   0.016599  -0.210   0.8339    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1003 on 390 degrees of freedom
##   (106 observations deleted due to missingness)
## Multiple R-squared:  0.3108, Adjusted R-squared:  0.3038 
## F-statistic: 43.97 on 4 and 390 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>In the context of voter turnout, everything is significant at 5% except for the open_seat variable. If it is a close election (based on our definition of 3 or less on the Likert Scale), voter turnout rate increased by 3.26%. For districts where the candidate is Incumbent republican, voter turnout increased by 3.46%, and where the elections were midterms, voter turnout decreased by 13.13%. Overall, based on the adjusted r squared, 30.38% of the variation was explained by our model. Based on the f-statistic, which is significant at the 0.1% level, all the variables of close election, the Repubican incumbent, and open seat variable.</p>
<pre><code>## 
## Call:
## lm(formula = voterTR ~ Close_E_D + Incumbent_D + MidtermE_D + 
##     Open_seat, data = Final_2012_2020_DF)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.28111 -0.05644  0.01246  0.07019  0.23198 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.626513   0.008446  74.183  &lt; 2e-16 ***
## Close_E_D    0.032630   0.015349   2.126  0.03414 *  
## Incumbent_D -0.034581   0.016127  -2.144  0.03263 *  
## MidtermE_D  -0.131268   0.010230 -12.832  &lt; 2e-16 ***
## Open_seat   -0.038064   0.013030  -2.921  0.00369 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1003 on 390 degrees of freedom
##   (106 observations deleted due to missingness)
## Multiple R-squared:  0.3108, Adjusted R-squared:  0.3038 
## F-statistic: 43.97 on 4 and 390 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Do expert predictions predict turnout?
Expert predictions (in whether or not the election is close or not here (dummy variable based on the Likert scale with anything greater than 3 and less than 5, 1 being the highest in support for Democrat and 5 for Republican) are significant at the 5% level. When the rating is in between lean democrat and lean republican, than close election actually had a positive impact on voter turnout rate by 3.26%.When a candidate was an incumbent Democrat, the voter turnout rate seems to decrease by 3.46%. When there is a midterm election, the voter turnout decreases by 13.13% and if the election is open seat, the turnout decreases by 3.81%.</p>
<p>The benefit of this model over the one below is that the open seat variable (whether or not there is currently someone in the position) is significant at the 1% level. The model here proved that the expert ratings about the election results was a good indicator in predicting the voter turnout rate because in a close election/more heated campaign, the model predicted a higher turnout rate.</p>
<pre><code>## 
## Call:
## lm(formula = voterTR ~ Close_E_D + Incumbent_D + MidtermE_D + 
##     est_cost_sum + Open_seat, data = Final_2012_2018_DF)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.274367 -0.059509  0.008876  0.067799  0.188061 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   5.697e-01  1.127e-02  50.549  &lt; 2e-16 ***
## Close_E_D     3.151e-02  1.649e-02   1.910   0.0571 .  
## Incumbent_D  -8.436e-02  1.686e-02  -5.003 1.01e-06 ***
## MidtermE_D   -7.626e-02  1.090e-02  -6.996 2.01e-11 ***
## est_cost_sum  2.943e-09  1.377e-09   2.137   0.0335 *  
## Open_seat    -3.177e-02  1.346e-02  -2.360   0.0190 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.09035 on 275 degrees of freedom
##   (220 observations deleted due to missingness)
## Multiple R-squared:  0.234,  Adjusted R-squared:  0.2201 
## F-statistic:  16.8 on 5 and 275 DF,  p-value: 1.73e-14</code></pre>
<p>Everything is the same as the model above, except the inclusion of one more variable, which is estimated cost for advertisement. The adjusted r squared slightly dropped to 22%,, but ad spends do help predict turnout here and are significat at the 5% level: every $10 million spent on advertisements. If the election is close, voter turnout increases by 3.15%, if the incumbent is a Democrat, turnout rate decreases by 8.44%, and if it is a midterm election, the turnout decreases by 7.63%. There is a hidden meaning here that actual voters who are easily motivated to turn out are probably Democrats. They turn out less when the incumbent is a Democrat, as shown by the model.</p>
<pre><code>## 
## Call:
## lm(formula = DemVotesMajorPercent ~ Close_E_D + LLS_D + Pres_D + 
##     GDP_Growth_Pct + US_CPI + US_Unemployment.Rate, data = Final_2012_2020_DF_ME_R1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -14.2619  -1.9945  -0.0702   1.9113  18.6393 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          108.54640    6.32723  17.155  &lt; 2e-16 ***
## Close_E_D             12.39792    0.38524  32.182  &lt; 2e-16 ***
## LLS_D                  6.21832    0.35369  17.581  &lt; 2e-16 ***
## Pres_D                -8.78989    1.02512  -8.575  &lt; 2e-16 ***
## GDP_Growth_Pct         6.88061    0.70626   9.742  &lt; 2e-16 ***
## US_CPI                -0.35633    0.03381 -10.540  &lt; 2e-16 ***
## US_Unemployment.Rate   0.47755    0.08122   5.880 7.58e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.373 on 494 degrees of freedom
##   (32 observations deleted due to missingness)
## Multiple R-squared:  0.6967, Adjusted R-squared:  0.693 
## F-statistic: 189.2 on 6 and 494 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre><code>## 
## Call:
## lm(formula = RepVotesMajorPercent ~ Close_E_D + LLS_R + Pres_R + 
##     GDP_Growth_Pct + US_CPI + US_Unemployment.Rate, data = Final_2012_2020_DF_ME_R1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -18.6393  -1.9113   0.0702   1.9945  14.2619 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          -5.97483    5.88148  -1.016     0.31    
## Close_E_D            -6.17960    0.39860 -15.503  &lt; 2e-16 ***
## LLS_R                 6.21832    0.35369  17.581  &lt; 2e-16 ***
## Pres_R               -8.78989    1.02512  -8.575  &lt; 2e-16 ***
## GDP_Growth_Pct       -6.88061    0.70626  -9.742  &lt; 2e-16 ***
## US_CPI                0.35633    0.03381  10.540  &lt; 2e-16 ***
## US_Unemployment.Rate -0.47755    0.08122  -5.880 7.58e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.373 on 494 degrees of freedom
##   (32 observations deleted due to missingness)
## Multiple R-squared:  0.6967, Adjusted R-squared:  0.693 
## F-statistic: 189.2 on 6 and 494 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Here, there is an inclusion of economic variables of GDP Growth Percentage, Consumer Price Index, and the U.S. Unemployment Rate which are based on national index, not in district or state. This model is an improvement from last week as 69.3% of both the Democrat and Republican majority vote share are explained by the variables of the close election dummy variable, the lean/likely/safety voters for each party, the President being either Democrat or Republican, and the economic variables all significant at the 0.1% level. The economic indicators are interesting because the increase in GDP Growth Percentage and Unemployment rate help increase Democrats’ vote share, while the CPI hurts the Democrats.</p>
